User.create(username: "Esther",email: "esther@gmail.com",password: "pray")
User.create(username: "Jo",email: "jo@jo.com",password: "Jesus")
User.create(username: "Dan",email: "dan@gmail.com",password: "Godisgood")
#
# emotions = ["Angry", "aggravated", "annoyed", "defiant", "disgusted", "enraged", "exasperated", "frustrated", "furious", "hateful", "hostile", "indignant", "infuriated", "mad", "obstinate", "outraged", "perturbed", "peeved", "pissed", "rebellious", "seething", "spiteful", "surly", "upset", "vengeful", "Ashamed", "apologetic", "embarrassed", "foolish", "guilty", "humble", "idiotic", "mortified", "regretful", "remorseful", "shameful", "worthless", "Confident", "bold", "capable", "centered", "eager", "energetic", "focused", "grounded", "hopeful", "inspired", "keen", "optimistic", "powerful", "productive", "strong", "sure", "trusting", "Confused", "baffled", "befuddled", "bewildered", "disoriented", "flustered", "perplexed", "puzzled", "scattered", "troubled", "unfocused", "Happy", "amused", "cheerful", "delighted"]
#
# emotion1 = ["ecstatic", "elated", "excited", "exuberant", "gleeful", "high", "joyful", "mischievous", "Hurt", "abandoned", "abused", "attacked", "belittled", "bitter", "cheated", "disappointed", "dismayed", "grieving", "gypped", "humiliated"]
# emotion2 =["mournful", "sorrowful", "rejected", "resentful", "Loving", "affectionate", "aroused", "caring", "devoted", "intimate", "tender", "warm", "Sad", "despondent", "depressed", "dismal", "low", "melancholy", "miserable", "unhappy", "weepy", "Satisfied", "adequate", "content", "mellow", "peaceful", "pleased", "Scared", "afraid", "alarmed", "fearful", "frightened", "horrified", "hysterical", "insecure", "intimidated", "nervous", "panicky", "petrified", "terrified", "threatened", "vulnerable", "Surprised", "aghast", "amazed", "astonished", "astounded", "incredulous", "shocked", "startled", "Thankful", "appreciative", "grateful", "gratified", "indebted", "obliged", "relieved", "Thoughtful", "challenged", "curious", "illuminated", "informed", "interested", "pensive", "reflective"]
# emotion3 = ["Uncertain", "cynical", "distrustful", "hesitant", "indecisive", "pessimistic", "skeptical", "suspicious", "unsure", "unsettled", "Uncaring", "ambivalent", "apathetic", "bored", "busy", "detached", "exhausted", "indifferent", "lethargic", "lazy"]
# emotion4 = ["tired", "unmotivated", "nonchalant", “occupied”, "unconcerned", "Wanting", "empty", "envious", "homesick", "hungry", "ignored", "jealous", "lonely", "longing", "lustful", "Weak", "inadequate", "burdened", "controlled", "despairing"]
# emotion5 = ["discouraged", "helpless", "hopeless", "impotent", "inhibited", "lost", “passive”, “restricted”, "Worried", "agitated", "anxious", "bothered", "restless", "tense", "uneasy", "unsettled"]
